# Generated by Django 5.2.3 on 2025-08-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed_at_task_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(choices=[(0, 'Not Started'), (25, 'In Progress - 25%'), (50, 'Halfway - 50%'), (75, 'Almost Done - 75%'), (100, 'Completed')], default=0),
        ),
    ]
