# Generated by Django 5.0.7 on 2025-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INTERN', 'Intern')], default='INTERN', max_length=10),
        ),
    ]
